// Generated by scripts/generate-site-config.js — do not edit by hand.
window.PHASE_SHIFT_SITE = {
  "ga4MeasurementId": "",
  "cloudflareBeaconToken": "",
  "privacyPath": "/blog/privacy/",
  "accentColor": "#5a7247",
  "denyButtonColor": "#666666"
};
